apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configs
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: user-workload-monitoring
          path: components/cluster-configs/user-workload-monitoring/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: models-staging
          path: tenants/models/overlays/staging
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: models-prod
          path: tenants/models/overlays/prod
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: guidellm-staging
          path: tenants/guidellm/overlays/staging
