apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store-gemma
  labels:
    opendatahub.io/dashboard: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
